### ISSUE TITLE
dataset for ssp

### ISSUE THREAD

**Issue by MLlover** [luizgh/sigver_wiwd#11]
Hi,
Will you make available the features extracted using SSP models for each of the four datasets?

Thanks

**Comment by luizgh** [comment]
Hello,

Yes, we will make them available (probably next week). I will comment on this thread when I add them to the Readme page.

**Comment by MLlover** [comment]
Thanks Luizgh,
Will you please upload the features extracted using SigNet-SPP-300dpi-F?

**Comment by luizgh** [comment]
Hello @MLlover - I just realized that I never answered this question. Unfortunately it takes quite some time to manage all these datasets, so for now on I will only provide the trained models - you can use the scripts to extract the features using any model / dataset. Thanks for understanding.
