### ISSUE TITLE
Unable to replicate using extracted features

### ISSUE THREAD

**Issue by gonultasbu** [luizgh/sigver_wiwd#15]
Hello,

I am trying to train and test a WD classifier using features extracted by Signet and Signet-F(0.95), however my error scores are usually a little bit higher (1.5-2.5%) than the reported scores on Vv (Table 5, EERglobalthreshold on paper). I am using:

 `C=1, class_weight='balanced', gamma=2**(-11)`

'balanced' option should match the skew according to the sklearn documentation. Both kernels have similar results.

Is this a normal behaviour or is there something else I might be missing?

Another question: GPDS960 consists of 960 users, according to the research group, but on your research paper, you state that there are 881 users, on the extracted features dataset, I can also see some missing user_id's, what's the reason for that?

Thanks a lot!

EDIT: I could replicate and even surpass the CEDAR scores by using:

`gamma='scale'`

which hints that my implementation is correct, in my opinion.

EDIT2: The errors are also a little bit higher for MCYT. For 10 signatures training, rbf kernel svm, my 10-fold average error is around 3.91%, compared to 2.87% reported on paper.

**Comment by gonultasbu** [comment]
Closing this since I managed to do it by introducing some randomness to the system, which means that I shuffled the intra-user signature id selections.

**Comment by luizgh** [comment]
I am glad it is solved. By the way, I have a new repository that contains the code to train and test WD classifiers. This might interest you: https://github.com/luizgh/sigver/
