### ISSUE TITLE
signet_spp_300dpi and signet_spp_600dpi

### ISSUE THREAD

**Issue by swagat123** [luizgh/sigver_wiwd#19]
Hi , is there any way i can use this signet_spp_300dpi and signet_spp_600dpi using tensor flow, as i do not want to use theano. My current setup is in tensorflow.

I appreciate  your suggestion.
Thanks

**Comment by luizgh** [comment]
Hello @swagat123 . In theory you could implement this model in Tensorflow and load the weights from the Theano model. You may need to implement the SPP layer in tensorflow (although someone may have implemented it already). Anyway, you probably would still need to install Theano, to verify that you get the same results with both models

**Comment by swagat123** [comment]
Thank you
