### ISSUE TITLE
how to train model for another handwritten data

### ISSUE THREAD

**Issue by JiteshPshah** [luizgh/sigver_wiwd#2]
I have data set of handwriting , I want to train the model . can you provide information on How do I train it ?

**Comment by luizgh** [comment]
Training a model with Lasagne is quite easy after you prepared your data and modeled your problem. I wrote a blog post on how to do this, that I believe will be helpful for you: https://luizgh.github.io/libraries/2015/12/08/getting-started-with-lasagne/
