### ISSUE TITLE
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

### ISSUE THREAD

**Issue by rvivek7** [luizgh/sigver_wiwd#5]
Hi,

I was trying to run example.py from PyCharm using windows.

Unfortunately I am getting the following error:
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

Could you help on how to set this?

Thanks in advance.
Regards,
Vivek

**Comment by luizgh** [comment]
Unfortunately I do not have a windows environment to simulate this error. However, it does seem to be a problem with the Theano installation in windows, for which you can find more information in this link: http://deeplearning.net/software/theano/install_windows.html

**Comment by luizgh** [comment]
I am closing this issue since it is related to the Theano installation, not an issue with the code from this repository.
