### ISSUE TITLE
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jashshah** [luizgh/sigver_wiwd#9]
Running Ubuntu 16.04. When running `python example.py` I get the below error:

```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    from preprocess.normalize import preprocess_signature
  File "/home/jash/Documents/Miscellaneous/sigver_wiwd/preprocess/normalize.py", line 1, in <module>
    import cv2
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory
```

Request you to help.

**Comment by luizgh** [comment]
It seems to be an issue with your opencv installation. Did you install it using conda? It should have installed all dependencies

**Comment by AyanSinhaMahapatra** [comment]
I got the same Error. 
It was installed using Conda 
`conda install -y opencv "scipy=0.18.0" "pillow=3.0.0"`
As specified in the Installation Guide. 
This should have installed all the dependencies. 
Doesn't look like any of these issues I guess.
[https://github.com/h5py/h5py/issues/672](url)
What can be the problem here?

**Comment by luizgh** [comment]
Hi Ayan, did you try it with a clean environment (e.g. creating a new environment with conda create)?

Btw, I would try the solution to re-install h5py, as discussed in the issue you mentioned:

pip uninstall h5py
pip install --no-cache-dir h5py

Let me know if it works

**Comment by AyanSinhaMahapatra** [comment]
Hi luizgh, thanks for the reply.

Yeah, I started in a clean Environment and did try reinstalling h5py as discussed in the issue, but none of them worked out. 

But I don't know why `pip install opencv-python` solved it. Even though I had already used 
`conda install -y opencv "scipy=0.18.0" "pillow=3.0.0"` before. 

This is so weird. What could possibly be the reason?

**Comment by luizgh** [comment]
Maybe the opencv package in conda is not properly listing all the dependencies. I will update the Readme to include this troubleshooting.

@jashshah let us know if installing opencv via pip resolves the problem for you.

**Comment by luizgh** [comment]
I changed the installation instructions to always install opencv using pip. This should resolve the problem.

**Comment by ZishuoLi** [comment]
plz try install h5py==2.6.0, I fix the problem through this

**Comment by BinSquare** [comment]
> plz try install h5py==2.6.0, I fix the problem through this

Resolved my issue. Running arch linux 5.2.9.-arch1-1-ARCH, x64 architecture. Installed opencv 4.1.1-1 using pacman.

**Comment by lhui2010** [comment]
> 



> plz try install h5py==2.6.0, I fix the problem through this

Resolved my issue with [msprime](https://github.com/tskit-dev/msprime)
